"use client";

import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, Check, ChevronLeft, ChevronRight, Loader2, Plus, Target, Trash2, TrendingUp, X } from "lucide-react";
import { saveDailyProgress, saveDailyTarget } from "@/app/actions/daily-targets";
import { Avatar } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Field, Input, Select, Textarea } from "@/components/ui/field";
import { runServerAction } from "@/lib/client-action";
import { dailyStatus, monthBounds, summarizeTargets, taskOptionsForRole, type DailyTargetStatus } from "@/lib/daily-targets";
import type { DailyTarget, Profile } from "@/lib/types";
import { cn } from "@/lib/utils";

type TargetTaskDraft = { key: string; id?: string; taskName: string; quantity: number; notes: string; custom: boolean };
type TargetDraft = { userId: string; date: string; tasks: TargetTaskDraft[] };
type ProgressDraft = { id?: string; userId: string; date: string; taskName: string; quantity: number; custom: boolean };

export function DailyTargetsClient({ profile, profiles, targets, month, today }: { profile: Profile; profiles: Profile[]; targets: DailyTarget[]; month: string; today: string }) {
  const router = useRouter(); const canManage = profile.role === "admin" || profile.role === "manager";
  const bounds = useMemo(() => monthBounds(month), [month]); const summaries = useMemo(() => summarizeTargets(profiles, targets, month, today), [profiles, targets, month, today]);
  const [targetDraft, setTargetDraft] = useState<TargetDraft | null>(null); const [progressDraft, setProgressDraft] = useState<ProgressDraft | null>(null);
  const totalTarget = summaries.reduce((sum, item) => sum + item.target, 0); const totalCompleted = summaries.reduce((sum, item) => sum + item.completed, 0); const onTarget = summaries.filter((item) => item.status === "on_target").length; const below = summaries.filter((item) => item.status === "below_target").length;
  const changeMonth = (offset: number) => { const [year, value] = month.split("-").map(Number); const next = new Date(Date.UTC(year, value - 1 + offset, 1)); router.push(`/targets?month=${next.getUTCFullYear()}-${String(next.getUTCMonth() + 1).padStart(2, "0")}`); };
  const newTarget = () => setTargetDraft({ userId: profiles[0]?.id ?? "", date: month === today.slice(0, 7) ? today : bounds.start, tasks: [emptyTargetTask()] });
  const newProgress = () => setProgressDraft({ userId: profile.id, date: today, taskName: "", quantity: 1, custom: false });
  return <main className="page-container"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-2xl font-semibold text-foreground">Daily targets</h1><p className="mt-1 text-sm text-muted-foreground">{canManage ? "Assign work and see who is on pace in real time." : "Your daily work and monthly progress, in one place."}</p></div><Button onClick={canManage ? newTarget : newProgress} disabled={canManage && !profiles.length}><Plus className="size-4" aria-hidden />{canManage ? "Assign target" : "Log completed work"}</Button></div>
    <section className="mt-6 flex items-center justify-between rounded-xl border border-border bg-card p-3 shadow-soft"><div className="flex items-center gap-1"><Button size="icon" variant="ghost" title="Previous month" onClick={() => changeMonth(-1)}><ChevronLeft className="size-4" /></Button><div className="min-w-36 text-center"><p className="text-sm font-semibold">{monthName(month)}</p><p className="text-xs text-muted-foreground">Monthly target sheet</p></div><Button size="icon" variant="ghost" title="Next month" onClick={() => changeMonth(1)}><ChevronRight className="size-4" /></Button></div><p className="hidden text-xs text-muted-foreground sm:block">Daily misses stay red; extra work counts toward the month.</p></section>
    <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Target />} label="Monthly target" value={totalTarget} note="Full selected-month target" /><Metric icon={<TrendingUp />} label="Completed" value={totalCompleted} note={`${totalTarget ? Math.round((totalCompleted / totalTarget) * 100) : 0}% of monthly target`} tone={totalCompleted >= totalTarget && totalTarget ? "success" : "default"} /><Metric icon={<Check />} label="On target" value={onTarget} note="At or above target due to date" tone="success" /><Metric icon={<AlertTriangle />} label="Below target" value={below} note="Needs recovery this month" tone={below ? "danger" : "success"} /></div>
    <section className="mt-6 overflow-hidden rounded-xl border border-border bg-card shadow-soft"><div className="border-b border-border px-4 py-4"><h2 className="font-semibold">Team target sheet</h2><p className="mt-1 text-xs text-muted-foreground">Each cell is completed / assigned. Every assigned task must be complete for the day to turn green.</p></div><div className="overflow-x-auto"><table className="min-w-max text-xs"><thead><tr className="border-b border-border bg-muted/40"><th className="sticky left-0 z-20 min-w-52 border-r border-border bg-muted px-4 py-3 text-left text-muted-foreground">Team member</th><th className="min-w-24 border-r border-border px-2 py-3 text-center text-muted-foreground">Month</th>{bounds.days.map((date) => <th key={date} className={cn("w-14 px-1 py-2 text-center", date === today && "bg-accent")}><span className="block text-muted-foreground">{weekday(date)}</span><span className="block text-sm">{Number(date.slice(-2))}</span></th>)}</tr></thead><tbody className="divide-y divide-border">{summaries.map((summary) => <tr key={summary.profile.id}><td className="sticky left-0 z-10 border-r border-border bg-card px-4 py-3"><div className="flex items-center gap-2"><Avatar name={summary.profile.name} src={summary.profile.avatar_url} className="size-8" /><div><p className="font-medium">{summary.profile.name}</p><p className="text-[11px] text-muted-foreground">{roleName(summary.profile.role)}</p></div></div></td><td className="border-r border-border px-2 text-center"><Badge status={summary.status} /><p className="mt-1 font-semibold">{summary.completed}/{summary.target}</p><p className="text-[10px] text-muted-foreground">{summary.percent}%</p></td>{bounds.days.map((date) => { const cell = summary.cells[date]; const shortCount = cell.shortTasks.length; const label = shortCount ? `${shortCount} short` : cell.status === "complete" ? "Done" : cell.status === "missed" ? "Missed" : cell.status === "in_progress" ? "Open" : "—"; return <td key={date} className="p-1"><div title={shortCount ? `Incomplete: ${cell.shortTasks.join(", ")}` : undefined} className={cn("flex h-11 w-12 flex-col items-center justify-center rounded-md border text-[10px]", cellTone(cell.status))}><span className="font-semibold">{cell.completed}/{cell.target}</span><span className="opacity-75">{label}</span></div></td>; })}</tr>)}</tbody></table></div></section>
    <section className="mt-6 overflow-hidden rounded-xl border border-border bg-card shadow-soft"><div className="flex items-center justify-between border-b border-border px-4 py-4"><div><h2 className="font-semibold">Daily entries</h2><p className="mt-1 text-xs text-muted-foreground">Completion is logged on the actual completion date.</p></div>{!canManage ? <Button size="sm" variant="secondary" onClick={newProgress}><Plus className="size-4" />Log extra work</Button> : null}</div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="border-b border-border bg-muted/40 text-xs text-muted-foreground"><tr><th className="px-4 py-3 text-left">Date</th>{canManage ? <th className="px-4 py-3 text-left">Person</th> : null}<th className="px-4 py-3 text-left">Task</th><th className="px-4 py-3 text-center">Target</th><th className="px-4 py-3 text-center">Completed</th><th className="px-4 py-3 text-center">Status</th><th className="px-4 py-3" /></tr></thead><tbody className="divide-y divide-border">{[...targets].sort((a,b) => b.target_date.localeCompare(a.target_date)).map((item) => { const person = profiles.find((candidate) => candidate.id === item.user_id); const custom = !taskOptionsForRole(person?.role).includes(item.task_name as never); return <Entry key={item.id} target={item} person={person} canManage={canManage} today={today} onTarget={() => setTargetDraft({ userId: item.user_id, date: item.target_date, tasks: [{ key: item.id, id: item.id, taskName: item.task_name, quantity: item.target_quantity, notes: item.notes ?? "", custom }] })} onProgress={() => setProgressDraft({ id: item.id, userId: item.user_id, date: item.target_date, taskName: item.task_name, quantity: item.manual_completed_quantity, custom })} />; })}</tbody></table></div>{!targets.length ? <p className="px-4 py-12 text-center text-sm text-muted-foreground">No targets have been entered this month.</p> : null}</section>
    {targetDraft ? <TargetDialog draft={targetDraft} profiles={profiles} onChange={setTargetDraft} onClose={() => setTargetDraft(null)} onDone={() => { setTargetDraft(null); router.refresh(); }} /> : null}{progressDraft ? <ProgressDialog draft={progressDraft} profiles={profiles} canManage={canManage} onChange={setProgressDraft} onClose={() => setProgressDraft(null)} onDone={() => { setProgressDraft(null); router.refresh(); }} /> : null}</main>;
}

function Entry({ target, person, canManage, today, onTarget, onProgress }: { target: DailyTarget; person?: Profile; canManage: boolean; today: string; onTarget: () => void; onProgress: () => void }) { const status = dailyStatus(target.target_quantity, target.completed_quantity, target.target_date, today); return <tr className="hover:bg-muted/30"><td className="px-4 py-3 text-muted-foreground">{shortDate(target.target_date)}</td>{canManage ? <td className="px-4 py-3 font-medium">{person?.name}</td> : null}<td className="px-4 py-3"><p className="font-medium">{target.task_name}</p>{target.notes ? <p className="text-xs text-muted-foreground">{target.notes}</p> : null}</td><td className="px-4 py-3 text-center font-semibold">{target.target_quantity || "—"}</td><td className="px-4 py-3 text-center font-semibold">{target.completed_quantity}</td><td className="px-4 py-3 text-center"><Badge status={status} /></td><td className="px-4 py-3 text-right"><Button size="sm" variant="ghost" onClick={onProgress}>Progress</Button>{canManage ? <Button size="sm" variant="ghost" onClick={onTarget}>Edit task</Button> : null}</td></tr>; }
function TargetDialog({ draft, profiles, onChange, onClose, onDone }: { draft: TargetDraft; profiles: Profile[]; onChange: (value: TargetDraft) => void; onClose: () => void; onDone: () => void }) {
  const [pending, start] = useTransition();
  const [message, setMessage] = useState("");
  const person = profiles.find((item) => item.id === draft.userId);
  const options = taskOptionsForRole(person?.role);
  const editing = draft.tasks.some((task) => Boolean(task.id));
  const updateTask = (key: string, change: Partial<TargetTaskDraft>) => onChange({ ...draft, tasks: draft.tasks.map((task) => task.key === key ? { ...task, ...change } : task) });
  const removeTask = (key: string) => onChange({ ...draft, tasks: draft.tasks.filter((task) => task.key !== key) });
  const submit = () => start(async () => {
    setMessage("");
    const result = await runServerAction(() => saveDailyTarget({ userId: draft.userId, date: draft.date, tasks: draft.tasks.map(({ id, taskName, quantity, notes }) => ({ id, taskName, quantity, notes })) }));
    if (result.ok) onDone(); else setMessage(result.message ?? "Could not save target.");
  });
  const invalid = !draft.userId || !draft.date || !draft.tasks.length || draft.tasks.some((task) => !task.taskName.trim());

  return <Dialog title={editing ? "Update assigned task" : "Assign daily targets"} onClose={onClose} wide>
    <div className="max-h-[70vh] overflow-y-auto p-5">
      <div className="grid gap-4 sm:grid-cols-2">
        <Field label="Team member"><Select value={draft.userId} onChange={(event) => onChange({ ...draft, userId: event.target.value, tasks: draft.tasks.map((task) => ({ ...task, taskName: "", custom: false })) })}>{profiles.map((item) => <option key={item.id} value={item.id}>{item.name} · {roleName(item.role)}</option>)}</Select></Field>
        <Field label="Date"><Input type="date" value={draft.date} onChange={(event) => onChange({ ...draft, date: event.target.value })} /></Field>
      </div>
      <div className="mt-5 space-y-3">
        {draft.tasks.map((task, index) => <section key={task.key} className="rounded-xl border border-border bg-muted/25 p-4">
          <div className="mb-3 flex items-center justify-between"><p className="text-sm font-semibold">Task {index + 1}</p>{draft.tasks.length > 1 ? <Button size="icon" variant="ghost" title="Remove task" onClick={() => removeTask(task.key)}><Trash2 className="size-4 text-destructive" /></Button> : null}</div>
          <div className="grid gap-4 sm:grid-cols-[minmax(0,1.2fr)_minmax(0,1.2fr)_120px]">
            <Field label="Task type"><Select value={task.custom ? "__custom__" : task.taskName} onChange={(event) => updateTask(task.key, event.target.value === "__custom__" ? { custom: true, taskName: "" } : { custom: false, taskName: event.target.value })}><option value="">Choose a task</option>{options.map((option) => <option key={option} value={option}>{option}</option>)}<option value="__custom__">Custom task…</option></Select></Field>
            {task.custom ? <Field label="Custom task"><Input value={task.taskName} onChange={(event) => updateTask(task.key, { taskName: event.target.value })} placeholder="Describe the task" /></Field> : <div className="hidden sm:block" />}
            <Field label="Quantity"><Input type="number" min={0} value={task.quantity} onChange={(event) => updateTask(task.key, { quantity: Number(event.target.value) })} /></Field>
            <div className="sm:col-span-3"><Field label="Notes"><Textarea className="min-h-16" value={task.notes} onChange={(event) => updateTask(task.key, { notes: event.target.value })} placeholder="Optional instructions" /></Field></div>
          </div>
        </section>)}
      </div>
      <Button className="mt-3" size="sm" variant="secondary" onClick={() => onChange({ ...draft, tasks: [...draft.tasks, emptyTargetTask()] })}><Plus className="size-4" />Add another task</Button>
      {message ? <p className="mt-4 text-sm text-destructive">{message}</p> : null}
      <p className="mt-4 text-xs text-muted-foreground">Standard tasks update automatically from completed workflow steps. Custom tasks remain manually updated.</p>
    </div>
    <Footer><Button variant="secondary" onClick={onClose}>Cancel</Button><Button disabled={pending || invalid} onClick={submit}>{pending ? <Loader2 className="size-4 animate-spin" /> : <Target className="size-4" />}{editing ? "Update task" : `Save ${draft.tasks.length} task${draft.tasks.length === 1 ? "" : "s"}`}</Button></Footer>
  </Dialog>;
}
function ProgressDialog({ draft, profiles, canManage, onChange, onClose, onDone }: { draft: ProgressDraft; profiles: Profile[]; canManage: boolean; onChange: (value: ProgressDraft) => void; onClose: () => void; onDone: () => void }) {
  const [pending,start] = useTransition(); const [message,setMessage] = useState("");
  const person = profiles.find((item) => item.id === draft.userId); const options = taskOptionsForRole(person?.role); const locked = Boolean(draft.id);
  const submit = () => start(async () => { const result = await runServerAction(() => saveDailyProgress(draft)); if (result.ok) onDone(); else setMessage(result.message ?? "Could not save progress."); });
  return <Dialog title="Log completed work" onClose={onClose}><div className="grid gap-4 p-5 sm:grid-cols-2">{canManage ? <Field label="Team member"><Select disabled={locked} value={draft.userId} onChange={(e) => onChange({...draft,userId:e.target.value,taskName:"",custom:false})}>{profiles.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field> : null}<Field label="Completion date"><Input disabled={locked} type="date" value={draft.date} onChange={(e) => onChange({...draft,date:e.target.value})} /></Field>{locked ? <Field label="Task"><Input disabled value={draft.taskName} /></Field> : <Field label="Task type"><Select value={draft.custom ? "__custom__" : draft.taskName} onChange={(e) => onChange({...draft,custom:e.target.value === "__custom__",taskName:e.target.value === "__custom__" ? "" : e.target.value})}><option value="">Choose a task</option>{options.map((option) => <option key={option} value={option}>{option}</option>)}<option value="__custom__">Custom task…</option></Select></Field>}{!locked && draft.custom ? <Field label="Custom task"><Input value={draft.taskName} onChange={(e) => onChange({...draft,taskName:e.target.value})} placeholder="Describe the task" /></Field> : null}<Field label="Manual completed quantity"><Input type="number" min={0} value={draft.quantity} onChange={(e) => onChange({...draft,quantity:Number(e.target.value)})} /></Field>{locked ? <p className="sm:col-span-2 text-xs text-muted-foreground">This changes only the manual count. Automatically completed workflow steps remain preserved.</p> : null}{message ? <p className="sm:col-span-2 text-sm text-destructive">{message}</p> : null}</div><Footer><Button variant="secondary" onClick={onClose}>Cancel</Button><Button disabled={pending || !draft.date || !draft.taskName.trim()} onClick={submit}>{pending ? <Loader2 className="size-4 animate-spin" /> : <Check className="size-4" />}Save progress</Button></Footer></Dialog>;
}
function Dialog({ title,onClose,children,wide=false }: { title:string;onClose:()=>void;children:React.ReactNode;wide?:boolean }) { return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-neutral-950/45 p-4 backdrop-blur-[2px]" role="dialog" aria-modal="true"><section className={cn("w-full rounded-xl border border-border bg-card shadow-float", wide ? "max-w-3xl" : "max-w-xl")}><div className="flex items-center justify-between border-b border-border px-5 py-4"><h2 className="text-lg font-semibold">{title}</h2><Button size="icon" variant="ghost" title="Close" onClick={onClose}><X className="size-5" /></Button></div>{children}</section></div>; }
function Footer({ children }: { children:React.ReactNode }) { return <div className="flex justify-end gap-2 border-t border-border px-5 py-4">{children}</div>; }
function Metric({ icon,label,value,note,tone="default" }: {icon:React.ReactNode;label:string;value:number;note:string;tone?:"default"|"success"|"danger"}) { return <section className="rounded-xl border border-border bg-card p-4 shadow-soft"><div className="flex items-center gap-2 text-xs text-muted-foreground"><span className={cn("flex size-8 items-center justify-center rounded-md",tone === "success" ? "bg-success/15 text-success" : tone === "danger" ? "bg-destructive/10 text-destructive" : "bg-accent text-accent-foreground")}>{icon}</span>{label}</div><p className={cn("mt-3 text-2xl font-semibold",tone === "success" ? "text-success" : tone === "danger" ? "text-destructive" : "text-foreground")}>{value}</p><p className="mt-1 text-xs text-muted-foreground">{note}</p></section>; }
function Badge({ status }: { status:string }) { const label = status === "on_target" ? "On target" : status === "below_target" ? "Below" : status === "complete" ? "Complete" : status === "missed" ? "Missed" : status === "in_progress" ? "In progress" : status === "scheduled" ? "Scheduled" : "No target"; return <span className={cn("inline-flex rounded-full px-2 py-0.5 text-[10px] font-medium",["on_target","complete"].includes(status) ? "bg-success/15 text-success" : ["below_target","missed"].includes(status) ? "bg-destructive/10 text-destructive" : status === "in_progress" ? "bg-warning/15 text-warning" : "bg-muted text-muted-foreground")}>{label}</span>; }
function cellTone(status: DailyTargetStatus) { return status === "complete" ? "border-success/30 bg-success/15 text-success" : status === "missed" ? "border-destructive/30 bg-destructive/10 text-destructive" : status === "in_progress" ? "border-warning/30 bg-warning/15 text-warning" : status === "scheduled" ? "border-border bg-muted/60 text-muted-foreground" : "border-transparent text-muted-foreground/60"; }
function emptyTargetTask(): TargetTaskDraft { return { key: crypto.randomUUID(), taskName: "", quantity: 1, notes: "", custom: false }; }
function roleName(role:Profile["role"]) { return role === "content_creator" ? "Creator" : role === "editor" ? "Editor" : role; } function monthName(value:string) { return new Intl.DateTimeFormat("en-IN",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}-01T00:00:00Z`)); } function weekday(value:string) { return new Intl.DateTimeFormat("en-IN",{weekday:"narrow",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`)); } function shortDate(value:string) { return new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"short",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`)); }
