"use client";

import Link from "next/link";
import { useMemo, useState, useTransition } from "react";
import { usePathname, useRouter } from "next/navigation";
import { Activity, AlarmClock, ArrowDown, ArrowRight, ArrowUp, CalendarDays, CheckCircle2, CircleHelp, Clock3, Filter, Gauge, Loader2, RotateCcw, Settings2, Target, X } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { updateAnalyticsSlaTargets } from "@/app/actions/admin";
import { runServerAction } from "@/lib/client-action";
import { ProductionStageBadge } from "@/components/workflow/production-stage";
import { Avatar } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Field, Input, Select } from "@/components/ui/field";
import type { AnalyticsDashboardModel, AnalyticsTab } from "@/lib/analytics";
import type { Campaign, Product, Profile } from "@/lib/types";
import { cn, formatDateOnly, formatDurationHours } from "@/lib/utils";

export function AnalyticsDashboard({ model, profile, products, campaigns, profiles }: { model: AnalyticsDashboardModel; profile: Profile; products: Product[]; campaigns: Campaign[]; profiles: Profile[] }) {
  const router = useRouter();
  const pathname = usePathname();
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [slaOpen, setSlaOpen] = useState(false);
  const [isNavigating, startNavigation] = useTransition();
  const creators = profiles.filter((item) => item.role === "content_creator");
  const editors = profiles.filter((item) => item.role === "editor");

  function updateQuery(updates: Record<string, string | null>) {
    const query = new URLSearchParams(window.location.search);
    Object.entries(updates).forEach(([key, value]) => value ? query.set(key, value) : query.delete(key));
    startNavigation(() => router.replace(`${pathname}?${query.toString()}`, { scroll: false }));
  }

  return (
    <main className="page-container">
      <div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between">
        <div><h1 className="text-2xl font-semibold text-foreground">Work overview</h1><p className="mt-1 text-sm text-muted-foreground">See how much work is moving, what is taking time, and what needs attention.</p></div>
        <div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => setFiltersOpen((value) => !value)}><Filter className="size-4" aria-hidden />Filters{activeFilterCount(model) ? <span className="rounded-full bg-border px-1.5 text-[10px]">{activeFilterCount(model)}</span> : null}</Button><Button variant="secondary" onClick={() => setSlaOpen(true)}><Settings2 className="size-4" aria-hidden />Time targets</Button></div>
      </div>

      <section className="panel mt-5 p-3">
        <div className="flex flex-col gap-3 xl:flex-row xl:items-end">
          <label className="min-w-44 flex-1"><span className="mb-1 block text-xs font-medium text-muted-foreground">Period</span><Select value={model.filters.range} onChange={(event) => updateQuery({ range: event.target.value, from: null, to: null })}><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="90d">Last 90 days</option><option value="this_month">This month</option><option value="last_month">Last month</option><option value="custom">Custom range</option></Select></label>
          {model.filters.range === "custom" ? <><label className="min-w-40"><span className="mb-1 block text-xs font-medium text-muted-foreground">From</span><Input type="date" value={model.filters.from} onChange={(event) => updateQuery({ from: event.target.value })} /></label><label className="min-w-40"><span className="mb-1 block text-xs font-medium text-muted-foreground">To</span><Input type="date" value={model.filters.to} onChange={(event) => updateQuery({ to: event.target.value })} /></label></> : <div className="flex h-10 items-center gap-2 rounded-md bg-muted px-3 text-sm text-muted-foreground"><CalendarDays className="size-4" aria-hidden />{formatDateOnly(model.filters.from)} – {formatDateOnly(model.filters.to)}</div>}
          {isNavigating ? <span className="inline-flex h-10 items-center gap-2 px-2 text-xs text-muted-foreground"><Loader2 className="size-4 animate-spin" aria-hidden />Updating</span> : null}
        </div>
        {filtersOpen ? <div className="mt-3 grid gap-3 border-t border-border pt-3 sm:grid-cols-2 xl:grid-cols-4"><FilterSelect label="Product" value={model.filters.productId} options={products.map((item) => ({ id: item.id, name: item.name }))} onChange={(value) => updateQuery({ product: value })} /><FilterSelect label="Campaign" value={model.filters.campaignId} options={campaigns.map((item) => ({ id: item.id, name: item.name }))} onChange={(value) => updateQuery({ campaign: value })} /><FilterSelect label="Creator" value={model.filters.creatorId} options={creators.map((item) => ({ id: item.id, name: item.name }))} onChange={(value) => updateQuery({ creator: value })} /><FilterSelect label="Editor" value={model.filters.editorId} options={editors.map((item) => ({ id: item.id, name: item.name }))} onChange={(value) => updateQuery({ editor: value })} /><div className="sm:col-span-2 xl:col-span-4"><Button size="sm" variant="ghost" onClick={() => updateQuery({ product: null, campaign: null, creator: null, editor: null })}><RotateCcw className="size-4" aria-hidden />Clear team and project filters</Button></div></div> : null}
      </section>

      <nav className="mt-5 flex w-full overflow-x-auto rounded-md border border-border bg-card p-1 sm:w-fit" aria-label="Analytics views">
        {(["overview", "team", "products"] as AnalyticsTab[]).map((tab) => <button key={tab} type="button" className={cn("h-9 whitespace-nowrap rounded px-4 text-sm font-medium", model.filters.tab === tab ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-muted")} onClick={() => updateQuery({ tab })}>{tab === "overview" ? "Overview" : tab === "team" ? "Team" : "Products & campaigns"}</button>)}
      </nav>

      {model.filters.tab === "overview" ? <Overview model={model} /> : model.filters.tab === "team" ? <TeamView model={model} /> : <ProductsView model={model} />}
      {slaOpen ? <SlaModal model={model} canEdit={profile.role === "admin"} onClose={() => setSlaOpen(false)} /> : null}
    </main>
  );
}

function Overview({ model }: { model: AnalyticsDashboardModel }) {
  return <>
    <section className="mt-5 grid gap-px overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6">
      <Kpi icon={CheckCircle2} label="Videos approved" description="Videos that received final manager or admin approval during this period." metric={model.kpis.approved} format="count" />
      <Kpi icon={Clock3} label="Typical completion time" description="The middle completion time from creating the item to final approval." metric={model.kpis.cycleHours} format="hours" lowerIsBetter />
      <Kpi icon={Target} label="Steps finished on time" description="Workflow steps completed within the time targets set by your admin." metric={model.kpis.slaCompliance} format="percent" />
      <Kpi icon={Gauge} label="Approved without changes" description="Approved videos that did not receive a change request." metric={model.kpis.firstPassRate} format="percent" />
      <Kpi icon={Activity} label="Work still open" description="All videos currently being prepared, edited, or reviewed." metric={model.kpis.workInProgress} format="count" lowerIsBetter />
      <Kpi icon={RotateCcw} label="Videos needing changes" description="Submitted videos that were sent back for one or more changes." metric={model.kpis.reworkRate} format="percent" lowerIsBetter />
    </section>

    <section className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.4fr)_minmax(360px,0.8fr)]">
      <div className="panel p-5"><SectionTitle title="Production flow" subtitle="Events completed in the selected period" /><div className="mt-4 h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={model.flow}><CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" vertical={false} /><XAxis dataKey="bucket" tick={{ fontSize: 11, fill: "hsl(var(--muted-foreground))" }} axisLine={false} tickLine={false} /><YAxis allowDecimals={false} tick={{ fontSize: 11, fill: "hsl(var(--muted-foreground))" }} axisLine={false} tickLine={false} /><Tooltip cursor={{ fill: "hsl(var(--muted))" }} contentStyle={{ background: "hsl(var(--popover))", border: "1px solid hsl(var(--border))", borderRadius: 8, color: "hsl(var(--popover-foreground))" }} /><Legend /><Bar dataKey="created" name="Created" fill="hsl(var(--muted-foreground))" radius={[3, 3, 0, 0]} /><Bar dataKey="handedOff" name="Handed off" fill="hsl(var(--primary))" radius={[3, 3, 0, 0]} /><Bar dataKey="submitted" name="Submitted" fill="hsl(var(--warning))" radius={[3, 3, 0, 0]} /><Bar dataKey="approved" name="Approved" fill="hsl(var(--success))" radius={[3, 3, 0, 0]} /></BarChart></ResponsiveContainer></div></div>
      <div className="panel overflow-hidden"><div className="border-b border-border px-5 py-4"><SectionTitle title="Deadline health" subtitle="Live deadlines and completed work" /></div><div className="grid grid-cols-3 gap-px bg-border"><SmallStat label="Due today" value={model.deadlineHealth.dueToday} /><SmallStat label="Due soon" value={model.deadlineHealth.dueSoon} /><SmallStat label="Overdue" value={model.deadlineHealth.overdue} tone={model.deadlineHealth.overdue ? "danger" : undefined} /></div><div className="px-5 py-5"><p className="text-xs font-medium text-muted-foreground">Approved on time</p><p className="mt-1 text-3xl font-semibold text-foreground">{percent(model.deadlineHealth.approvedOnTimeRate)}</p><p className="mt-1 text-xs text-muted-foreground">Based on {model.deadlineHealth.approvedOnTimeSample} approved videos with deadlines</p></div></div>
    </section>

    <section className="mt-5 grid gap-5 xl:grid-cols-2">
      <div className="panel overflow-hidden"><div className="border-b border-border px-5 py-4"><SectionTitle title="Time spent at each step" subtitle="Typical time, slower cases, and how often work met its target" /></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-muted text-xs text-muted-foreground"><tr><th className="px-5 py-3">Step</th><th className="px-4 py-3">Typical time</th><th className="px-4 py-3"><span className="inline-flex items-center gap-1">Slower cases<InfoTip text="75% of completed items took this long or less. The slowest 25% took longer." /></span></th><th className="px-4 py-3">Finished on time</th><th className="px-4 py-3">Items measured</th></tr></thead><tbody className="divide-y divide-border">{model.stageTurnaround.map((row) => <tr key={row.stage}><td className="px-5 py-3 font-medium text-foreground">{row.label}</td><td className="px-4 py-3">{duration(row.medianHours)}</td><td className="px-4 py-3">{duration(row.p75Hours)}</td><td className="px-4 py-3">{percent(row.compliance)}</td><td className="px-4 py-3 text-muted-foreground">{row.sample}</td></tr>)}</tbody></table></div></div>
      <div className="panel overflow-hidden"><div className="border-b border-border px-5 py-4"><SectionTitle title="Live work in progress" subtitle="Current backlog, regardless of selected period" /></div><div className="divide-y divide-border">{model.liveWip.map((row) => <div key={row.stage} className="grid grid-cols-[minmax(0,1fr)_auto_auto] items-center gap-4 px-5 py-3"><div><p className="text-sm font-medium text-foreground">{row.label}</p><p className="text-xs text-muted-foreground">Median age {duration(row.medianAgeHours)}{row.targetHours ? ` · ${row.targetHours}h target` : ""}</p></div><span className="text-lg font-semibold text-foreground">{row.count}</span><span className={cn("min-w-16 text-right text-xs font-medium", row.breached ? "text-destructive" : "text-muted-foreground")}>{row.breached ? `${row.breached} breached` : "On track"}</span></div>)}{!model.liveWip.length ? <Empty label="No active work" /> : null}</div></div>
    </section>

    <section className="panel mt-5 overflow-hidden"><div className="flex items-center justify-between border-b border-border px-5 py-4"><SectionTitle title="Bottlenecks requiring attention" subtitle="Current work ordered by SLA risk and stage age" /><AlarmClock className="size-5 text-muted-foreground" aria-hidden /></div><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-muted text-xs text-muted-foreground"><tr><th className="px-5 py-3">Creative</th><th className="px-4 py-3">Stage</th><th className="px-4 py-3">Owner</th><th className="px-4 py-3">Age / target</th><th className="px-4 py-3">Deadline</th><th className="px-4 py-3">Risk</th><th className="px-4 py-3" /></tr></thead><tbody className="divide-y divide-border">{model.bottlenecks.map((item) => <tr key={item.id} className="hover:bg-muted"><td className="px-5 py-3"><p className="font-medium text-foreground">{item.name}</p><p className="text-xs text-muted-foreground">{item.product} · {item.campaign}</p></td><td className="px-4 py-3"><ProductionStageBadge stage={item.stage} /></td><td className="px-4 py-3 text-muted-foreground">{item.owner}</td><td className="px-4 py-3">{duration(item.ageHours)}{item.targetHours ? ` / ${item.targetHours}h` : ""}</td><td className="px-4 py-3 text-muted-foreground">{item.deadline ? formatDateOnly(item.deadline) : "No deadline"}</td><td className="px-4 py-3"><RiskBadge severity={item.severity} /></td><td className="px-4 py-3 text-right"><Link href={`/ads/${item.id}`} className="inline-flex items-center gap-1 text-xs font-medium text-primary hover:underline">Open<ArrowRight className="size-3.5" aria-hidden /></Link></td></tr>)}</tbody></table>{!model.bottlenecks.length ? <Empty label="No bottlenecks" /> : null}</div></section>
  </>;
}

function TeamView({ model }: { model: AnalyticsDashboardModel }) {
  const [editorSort, setEditorSort] = useState("active");
  const [creatorSort, setCreatorSort] = useState("preparing");
  const editors = useMemo(() => [...model.editors].sort((a, b) => editorSort === "completed" ? b.completed - a.completed : editorSort === "turnaround" ? nullableSort(a.medianEditHours, b.medianEditHours) : b.activeAssignments - a.activeAssignments), [editorSort, model.editors]);
  const creators = useMemo(() => [...model.creators].sort((a, b) => creatorSort === "shoots" ? b.completedShoots - a.completedShoots : creatorSort === "review" ? nullableSort(a.medianReviewHours, b.medianReviewHours) : b.preparing - a.preparing), [creatorSort, model.creators]);
  return <div className="mt-5 space-y-5"><TeamTable title="Editors" subtitle="Capacity, delivery speed, quality, and SLA pressure" sort={editorSort} onSort={setEditorSort} options={[{ value: "active", label: "Active workload" }, { value: "completed", label: "Completed" }, { value: "turnaround", label: "Edit turnaround" }]} headers={["Editor", "Capacity", "Completed", "Median edit", "First pass", "Avg revisions", "SLA breaches"]} rows={editors.map((item) => [<Person key="person" name={item.name} avatar={item.avatarUrl} />, `${item.inProgress}/${item.capacity} in progress · ${item.activeAssignments} assigned`, item.completed, duration(item.medianEditHours), percent(item.firstPassRate), decimal(item.avgRevisions), item.slaBreaches])} /><TeamTable title="Content creators" subtitle="Current preparation, handoffs, reviews, and rework" sort={creatorSort} onSort={setCreatorSort} options={[{ value: "preparing", label: "Preparing workload" }, { value: "shoots", label: "Shoots completed" }, { value: "review", label: "Review turnaround" }]} headers={["Creator", "Preparing", "With editor", "Needs review", "Shoots completed", "Median review", "Rework rate"]} rows={creators.map((item) => [<Person key="person" name={item.name} avatar={item.avatarUrl} />, item.preparing, item.withEditor, item.needsReview, item.completedShoots, duration(item.medianReviewHours), percent(item.reworkRate)])} /></div>;
}

function ProductsView({ model }: { model: AnalyticsDashboardModel }) {
  const [sort, setSort] = useState("wip");
  const sortRows = (rows: AnalyticsDashboardModel["products"]) => [...rows].sort((a, b) => sort === "approved" ? b.approved - a.approved : sort === "cycle" ? nullableSort(a.medianCycleHours, b.medianCycleHours) : b.wip - a.wip);
  return <div className="mt-5 space-y-5"><AggregateTable title="Products" subtitle="Creative demand and production health by product" rows={sortRows(model.products)} sort={sort} onSort={setSort} /><AggregateTable title="Campaigns" subtitle="Creative progress and rework by campaign" rows={sortRows(model.campaigns)} sort={sort} onSort={setSort} /></div>;
}

function AggregateTable({ title, subtitle, rows, sort, onSort }: { title: string; subtitle: string; rows: AnalyticsDashboardModel["products"]; sort: string; onSort: (value: string) => void }) {
  return <section className="panel overflow-hidden"><div className="flex flex-col gap-3 border-b border-border px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><SectionTitle title={title} subtitle={subtitle} /><Select className="w-full sm:w-44" value={sort} onChange={(event) => onSort(event.target.value)}><option value="wip">Sort: Current WIP</option><option value="approved">Sort: Approved</option><option value="cycle">Sort: Cycle time</option></Select></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-muted text-xs text-muted-foreground"><tr><th className="px-5 py-3">Name</th><th className="px-4 py-3">Started</th><th className="px-4 py-3">Current WIP</th><th className="px-4 py-3">Approved</th><th className="px-4 py-3">Approval rate</th><th className="px-4 py-3">Median cycle</th><th className="px-4 py-3">First pass</th><th className="px-4 py-3">Avg revisions</th></tr></thead><tbody className="divide-y divide-border">{rows.map((item) => <tr key={item.id}><td className="px-5 py-3 font-medium text-foreground">{item.name}</td><td className="px-4 py-3">{item.started}</td><td className="px-4 py-3">{item.wip}</td><td className="px-4 py-3">{item.approved}</td><td className="px-4 py-3">{percent(item.approvalRate)}</td><td className="px-4 py-3">{duration(item.medianCycleHours)}</td><td className="px-4 py-3">{percent(item.firstPassRate)}</td><td className="px-4 py-3">{decimal(item.avgRevisions)}</td></tr>)}</tbody></table>{!rows.length ? <Empty label={`No ${title.toLowerCase()} in this view`} /> : null}</div></section>;
}

function SlaModal({ model, canEdit, onClose }: { model: AnalyticsDashboardModel; canEdit: boolean; onClose: () => void }) {
  const [values, setValues] = useState({ assignmentStartHours: model.slaTargets.ready_for_edit, editingHours: model.slaTargets.editing, creatorReviewHours: model.slaTargets.creator_review, finalReviewHours: model.slaTargets.final_review, revisionHours: model.slaTargets.changes_requested });
  const [message, setMessage] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();
  function save() { startTransition(async () => { const response = await runServerAction(() => updateAnalyticsSlaTargets(values)); if (!response.ok) setMessage(response.message ?? "Unable to save time targets."); else { setMessage("Time targets saved."); setTimeout(onClose, 500); } }); }
  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-neutral-950/45 p-4 backdrop-blur-[2px]" role="dialog" aria-modal="true" aria-labelledby="sla-title"><section className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-xl border border-border bg-card shadow-float dark:shadow-none"><div className="flex items-start justify-between gap-3 border-b border-border px-5 py-4"><div><h2 id="sla-title" className="text-lg font-semibold text-foreground">Time targets</h2><p className="mt-1 text-sm text-muted-foreground">Set the expected maximum time for each step. Late items appear in Work needing attention.</p></div><Button size="icon" variant="ghost" title="Close" onClick={onClose}><X className="size-5" aria-hidden /></Button></div><div className="grid gap-4 p-5 sm:grid-cols-2"><SlaField label="Start after assignment" value={values.assignmentStartHours} disabled={!canEdit} onChange={(value) => setValues((current) => ({ ...current, assignmentStartHours: value }))} /><SlaField label="Finish first edit" value={values.editingHours} disabled={!canEdit} onChange={(value) => setValues((current) => ({ ...current, editingHours: value }))} /><SlaField label="Content creator review" value={values.creatorReviewHours} disabled={!canEdit} onChange={(value) => setValues((current) => ({ ...current, creatorReviewHours: value }))} /><SlaField label="Manager or admin review" value={values.finalReviewHours} disabled={!canEdit} onChange={(value) => setValues((current) => ({ ...current, finalReviewHours: value }))} /><SlaField label="Complete requested changes" value={values.revisionHours} disabled={!canEdit} onChange={(value) => setValues((current) => ({ ...current, revisionHours: value }))} />{message ? <p className="self-end rounded-md bg-muted px-3 py-2 text-sm text-muted-foreground">{message}</p> : null}</div><div className="flex justify-end gap-2 border-t border-border px-5 py-4"><Button variant="secondary" onClick={onClose}>{canEdit ? "Cancel" : "Close"}</Button>{canEdit ? <Button disabled={isPending || Object.values(values).some((value) => value < 1 || value > 720)} onClick={save}>{isPending ? <Loader2 className="size-4 animate-spin" aria-hidden /> : null}Save targets</Button> : null}</div></section></div>;
}

function Kpi({ icon: Icon, label, description, metric, format, lowerIsBetter }: { icon: typeof Activity; label: string; description: string; metric: AnalyticsDashboardModel["kpis"][keyof AnalyticsDashboardModel["kpis"]]; format: "count" | "hours" | "percent"; lowerIsBetter?: boolean }) {
  const value = format === "hours" ? duration(metric.value) : format === "percent" ? percent(metric.value) : metric.value?.toString() ?? "—";
  const good = metric.delta === null || metric.delta === 0 ? null : lowerIsBetter ? metric.delta < 0 : metric.delta > 0;
  return <div className="bg-card p-4"><span className="flex size-9 items-center justify-center rounded-md bg-muted text-muted-foreground"><Icon className="size-[18px]" aria-hidden /></span><div className="mt-3 flex items-center gap-1.5"><p className="text-xs font-medium text-muted-foreground">{label}</p><InfoTip text={description} /></div><p className="mt-1 text-2xl font-semibold text-foreground">{value}</p><div className="mt-2 flex items-center justify-between gap-2 text-[11px]"><span className={cn("inline-flex items-center gap-0.5 font-medium", good === true ? "text-success" : good === false ? "text-destructive" : "text-muted-foreground")}>{metric.delta === null || metric.delta === 0 ? "No change from previous period" : <>{metric.delta > 0 ? <ArrowUp className="size-3" aria-hidden /> : <ArrowDown className="size-3" aria-hidden />}{format === "hours" ? duration(Math.abs(metric.delta)) : format === "percent" ? `${Math.abs(metric.delta).toFixed(0)} points` : Math.abs(metric.delta)}</>}</span><span className="text-muted-foreground" title="Number of items used for this calculation">{metric.sample} measured</span></div></div>;
}

function TeamTable({ title, subtitle, sort, onSort, options, headers, rows }: { title: string; subtitle: string; sort: string; onSort: (value: string) => void; options: { value: string; label: string }[]; headers: string[]; rows: (string | number | React.ReactNode)[][] }) {
  return <section className="panel overflow-hidden"><div className="flex flex-col gap-3 border-b border-border px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><SectionTitle title={title} subtitle={subtitle} /><Select className="w-full sm:w-48" value={sort} onChange={(event) => onSort(event.target.value)}>{options.map((option) => <option key={option.value} value={option.value}>Sort: {option.label}</option>)}</Select></div><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-muted text-xs text-muted-foreground"><tr>{headers.map((header) => <th key={header} className="px-4 py-3 first:pl-5">{header}</th>)}</tr></thead><tbody className="divide-y divide-border">{rows.map((row, rowIndex) => <tr key={rowIndex}>{row.map((cell, index) => <td key={index} className="px-4 py-3 first:pl-5">{cell}</td>)}</tr>)}</tbody></table>{!rows.length ? <Empty label={`No ${title.toLowerCase()} available`} /> : null}</div></section>;
}

function FilterSelect({ label, value, options, onChange }: { label: string; value: string | null; options: { id: string; name: string }[]; onChange: (value: string | null) => void }) { return <label><span className="mb-1 block text-xs font-medium text-muted-foreground">{label}</span><Select value={value ?? ""} onChange={(event) => onChange(event.target.value || null)}><option value="">All {label.toLowerCase()}s</option>{options.map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</Select></label>; }
function SlaField({ label, value, disabled, onChange }: { label: string; value: number; disabled: boolean; onChange: (value: number) => void }) { return <Field label={label} hint="Maximum hours"><Input type="number" min={1} max={720} disabled={disabled} value={value} onChange={(event) => onChange(Number(event.target.value))} /></Field>; }
function InfoTip({ text }: { text: string }) { return <button type="button" className="inline-flex size-5 items-center justify-center rounded text-muted-foreground hover:bg-muted hover:text-muted-foreground" title={text} aria-label={text}><CircleHelp className="size-3.5" aria-hidden /></button>; }
function SectionTitle({ title, subtitle }: { title: string; subtitle: string }) { return <div><h2 className="section-heading">{title}</h2><p className="mt-1 text-xs text-muted-foreground">{subtitle}</p></div>; }
function SmallStat({ label, value, tone }: { label: string; value: number; tone?: "danger" }) { return <div className="bg-card px-4 py-4"><p className="text-xs text-muted-foreground">{label}</p><p className={cn("mt-1 text-2xl font-semibold", tone === "danger" ? "text-destructive" : "text-foreground")}>{value}</p></div>; }
function RiskBadge({ severity }: { severity: "healthy" | "at_risk" | "breached" }) { return <span className={cn("inline-flex rounded-full px-2 py-1 text-xs font-medium", severity === "breached" ? "bg-destructive/10 text-destructive" : severity === "at_risk" ? "bg-warning/15 text-warning" : "bg-success/15 text-success")}>{severity === "at_risk" ? "At risk" : severity === "breached" ? "Breached" : "Healthy"}</span>; }
function Person({ name, avatar }: { name: string; avatar: string | null }) { return <div className="flex min-w-40 items-center gap-2"><Avatar name={name} src={avatar} className="size-8" /><span className="font-medium text-foreground">{name}</span></div>; }
function Empty({ label }: { label: string }) { return <div className="px-5 py-10 text-center text-sm text-muted-foreground">{label}</div>; }
function duration(value: number | null) { return value === null ? "Insufficient data" : formatDurationHours(value); }
function percent(value: number | null) { return value === null ? "Insufficient data" : `${Math.round(value)}%`; }
function decimal(value: number | null) { return value === null ? "Insufficient data" : value.toFixed(1); }
function nullableSort(a: number | null, b: number | null) { if (a === null) return 1; if (b === null) return -1; return a - b; }
function activeFilterCount(model: AnalyticsDashboardModel) { return [model.filters.productId, model.filters.campaignId, model.filters.creatorId, model.filters.editorId].filter(Boolean).length; }
